language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - ARTIFACTORY_URL=https://rpmb.jfrog.io
    - OS7=7.9.2009
    - OS8=stream8
    - OS7TAG=7.9.2009
    - OS8TAG=stream8
  jobs:
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php74custom BUILD=centos7msgpack      UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.yml       BINTRAY_REPO=php74custom BUILD=stream8msgpack      UPLOADER=stream8bintray REPO_PATH=centos/8-stream
    - BUILD_COMPOSE_FILE=docker-compose.php81.yml BINTRAY_REPO=php81custom BUILD=centos7msgpackphp81 UPLOADER=centos7bintray
    - BUILD_COMPOSE_FILE=docker-compose.php81.yml BINTRAY_REPO=php81custom BUILD=stream8msgpackphp81 UPLOADER=stream8bintray REPO_PATH=centos/8-stream

before_script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} build --no-cache ${BUILD}

script:
  - docker-compose -f ${BUILD_COMPOSE_FILE} up --exit-code-from ${BUILD} ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e ARTIFACTORY_URL=$ARTIFACTORY_URL ${UPLOADER}
  on:
    all_branches: true

jobs:
  include:
    - stage: docker
      script:
        - docker-compose -f build/php74/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php74/docker-compose.yml push
        on:
          all_branches: true
    - stage: docker
      script:
        - docker-compose -f build/php81/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/php81/docker-compose.yml push
        on:
          all_branches: true