version: 2.1

orbs:
  docker-rpmbuild: aursu/rpmbuild@1.1.7

parameters:
  artifactory-url:
    description: Artifactory URL
    type: string
    default: https://rpmb.jfrog.io

workflows:
  msgpackbuild:
    jobs:
      - docker-rpmbuild/build:
          name: centos7msgpack
          build_service: centos7msgpack
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8msgpack
          build_service: centos8msgpack
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7msgpackphp73
          build_file: docker-compose.php73.yml
          build_service: centos7msgpackphp73
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8msgpackphp73
          build_file: docker-compose.php73.yml
          build_service: centos8msgpackphp73
          bintray_uploader: centos8bintray
      - docker-rpmbuild/build:
          name: centos7msgpackphp80
          build_file: docker-compose.php80.yml
          build_service: centos7msgpackphp80
          bintray_uploader: centos7bintray
      - docker-rpmbuild/build:
          name: centos8msgpackphp80
          build_file: docker-compose.php80.yml
          build_service: centos8msgpackphp80
          bintray_uploader: centos8bintray
      - docker-rpmbuild/image:
          name: centos7msgpackphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos7msgpackphp74build
          requires:
            - centos7msgpack
      - docker-rpmbuild/image:
          name: centos8msgpackphp74build
          compose_file: build/php74/docker-compose.yml
          build_service: centos8msgpackphp74build
          requires:
            - centos8msgpack
      - docker-rpmbuild/image:
          name: centos7msgpackphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos7msgpackphp73build
          requires:
            - centos7msgpackphp73
      - docker-rpmbuild/image:
          name: centos8msgpackphp73build
          compose_file: build/php73/docker-compose.yml
          build_service: centos8msgpackphp73build
          requires:
            - centos8msgpackphp73
      - docker-rpmbuild/image:
          name: centos7msgpackphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos7msgpackphp80build
          requires:
            - centos7msgpackphp80
      - docker-rpmbuild/image:
          name: centos8msgpackphp80build
          compose_file: build/php80/docker-compose.yml
          build_service: centos8msgpackphp80build
          requires:
            - centos8msgpackphp80